"""初始化用户和授权表

Revision ID: 0a882f19c017
Revises: 
Create Date: 2026-04-21 16:11:34.648577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a882f19c017'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('nickname', sa.String(length=50), nullable=False, comment='昵称'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像URL'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='系统角色: admin/staff/customer'),
    sa.Column('position_desc', sa.String(length=100), nullable=True, comment='具体职位或身份描述(如: 高级宠物美容师/普通会员)'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活(用于逻辑删除)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户基础信息表'
    )
    op.create_table('user_auths',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='关联的用户ID'),
    sa.Column('identity_type', sa.String(length=20), nullable=False, comment='登录类型: password(网页端) / wechat(小程序)'),
    sa.Column('identifier', sa.String(length=100), nullable=False, comment='标识符: 账号/手机号/邮箱 或 微信的OpenID'),
    sa.Column('credential', sa.String(length=255), nullable=True, comment='密码凭证: 哈希加密后的密码 或 微信的Session_Key(可选)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户登录授权表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_auths')
    op.drop_table('users')
    # ### end Alembic commands ###
