"""用户表新增细粒度权限

Revision ID: 4b7c84c8758c
Revises: 0a882f19c017
Create Date: 2026-04-21 20:18:00.541776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b7c84c8758c'
down_revision: Union[str, Sequence[str], None] = '0a882f19c017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('permissions', sa.JSON(), nullable=True, comment='细粒度权限列表'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'permissions')
    # ### end Alembic commands ###
