"""新增订单和订单明细表

Revision ID: 518374ae002d
Revises: 90459091ad0d
Create Date: 2026-05-13 17:36:44.053047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '518374ae002d'
down_revision: Union[str, Sequence[str], None] = '90459091ad0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('order_no', sa.String(length=30), nullable=False, comment='订单编号'),
    sa.Column('store_id', sa.Integer(), nullable=False, comment='所属门店'),
    sa.Column('order_type', sa.String(length=20), nullable=False, comment='类型: sale(销售) / service(服务)'),
    sa.Column('customer_id', sa.Integer(), nullable=True, comment='客户ID(可为空，散客)'),
    sa.Column('total_amount', sa.Float(), nullable=False, comment='订单总金额'),
    sa.Column('discount_amount', sa.Float(), nullable=True, comment='优惠金额'),
    sa.Column('final_amount', sa.Float(), nullable=False, comment='实付金额'),
    sa.Column('payment_method', sa.String(length=20), nullable=False, comment='支付方式: cash/wechat/alipay/card/balance'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: pending/paid/completed/cancelled/refunded'),
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='经手店员'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no'),
    comment='订单表(销售订单/服务订单)'
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='订单ID'),
    sa.Column('item_type', sa.String(length=20), nullable=False, comment='明细类型: product / service'),
    sa.Column('product_id', sa.Integer(), nullable=True, comment='商品ID'),
    sa.Column('service_id', sa.Integer(), nullable=True, comment='服务ID'),
    sa.Column('quantity', sa.Integer(), nullable=True, comment='数量'),
    sa.Column('unit_price', sa.Float(), nullable=False, comment='单价'),
    sa.Column('subtotal', sa.Float(), nullable=False, comment='小计'),
    sa.Column('staff_id', sa.Integer(), nullable=True, comment='负责店员(服务类)'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='订单明细表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('orders')
    # ### end Alembic commands ###
