"""修改宠物模型

Revision ID: 57bf5d98004f
Revises: b8a146d43e7b
Create Date: 2026-05-12 15:32:48.592593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '57bf5d98004f'
down_revision: Union[str, Sequence[str], None] = 'b8a146d43e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('ownership_type', sa.String(length=20), nullable=False, comment='归属类型: customer(客宠) / for_sale(待售) / store_mascot(店宠)'))
    op.add_column('pets', sa.Column('price', sa.Float(), nullable=True, comment='售价(仅待售宠物有效)'))
    op.alter_column('pets', 'owner_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='关联客户的主键(店内宠物为空)',
               existing_comment='关联客户的主键')
    op.alter_column('pets', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True,
               comment='宠物昵称(待售宠物可能暂无名字)',
               existing_comment='宠物昵称')
    op.alter_column('pets', 'weight',
               existing_type=mysql.FLOAT(),
               comment='体重(kg)',
               existing_comment='体重(kg)，影响洗护价格',
               existing_nullable=True)
    op.alter_column('pets', 'birth_date',
               existing_type=sa.DATE(),
               comment='出生日期',
               existing_comment='出生日期(用于计算年龄和发生日祝福)',
               existing_nullable=True)
    op.alter_column('pets', 'vaccine_status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='疫苗接种状态',
               existing_comment='疫苗接种状态描述或简述',
               existing_nullable=True)
    op.alter_column('pets', 'special_notes',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='特殊注意事项',
               existing_comment='特殊注意事项(如: 咬人/皮肤病/过敏史)',
               existing_nullable=True)
    op.drop_constraint(op.f('pets_ibfk_1'), 'pets', type_='foreignkey')
    op.create_foreign_key(None, 'pets', 'customer_profiles', ['owner_id'], ['id'], ondelete='SET NULL')
    op.create_table_comment(
        'pets',
        '宠物档案与资产表',
        existing_comment='宠物档案表',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'pets',
        '宠物档案表',
        existing_comment='宠物档案与资产表',
        schema=None
    )
    op.drop_constraint(None, 'pets', type_='foreignkey')
    op.create_foreign_key(op.f('pets_ibfk_1'), 'pets', 'customer_profiles', ['owner_id'], ['id'], ondelete='CASCADE')
    op.alter_column('pets', 'special_notes',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='特殊注意事项(如: 咬人/皮肤病/过敏史)',
               existing_comment='特殊注意事项',
               existing_nullable=True)
    op.alter_column('pets', 'vaccine_status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='疫苗接种状态描述或简述',
               existing_comment='疫苗接种状态',
               existing_nullable=True)
    op.alter_column('pets', 'birth_date',
               existing_type=sa.DATE(),
               comment='出生日期(用于计算年龄和发生日祝福)',
               existing_comment='出生日期',
               existing_nullable=True)
    op.alter_column('pets', 'weight',
               existing_type=mysql.FLOAT(),
               comment='体重(kg)，影响洗护价格',
               existing_comment='体重(kg)',
               existing_nullable=True)
    op.alter_column('pets', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False,
               comment='宠物昵称',
               existing_comment='宠物昵称(待售宠物可能暂无名字)')
    op.alter_column('pets', 'owner_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='关联客户的主键',
               existing_comment='关联客户的主键(店内宠物为空)')
    op.drop_column('pets', 'price')
    op.drop_column('pets', 'ownership_type')
    # ### end Alembic commands ###
