"""添加库存管理表(分类/物品/流水)

Revision ID: 8d85e8226903
Revises: c7f77ae5f35c
Create Date: 2026-05-13 15:10:09.483972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d85e8226903'
down_revision: Union[str, Sequence[str], None] = 'c7f77ae5f35c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='分类名称(如:狗粮、猫砂、药品)'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='分类描述'),
    sa.Column('store_id', sa.Integer(), nullable=False, comment='所属门店'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='库存分类表'
    )
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='所属分类'),
    sa.Column('store_id', sa.Integer(), nullable=False, comment='所属门店'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='物品名称'),
    sa.Column('sku', sa.String(length=50), nullable=False, comment='SKU编码'),
    sa.Column('unit', sa.String(length=20), nullable=True, comment='单位(袋/瓶/支/盒)'),
    sa.Column('quantity', sa.Float(), nullable=True, comment='当前库存数量'),
    sa.Column('safety_stock', sa.Float(), nullable=True, comment='安全库存阈值'),
    sa.Column('unit_price', sa.Float(), nullable=True, comment='进货单价'),
    sa.Column('selling_price', sa.Float(), nullable=True, comment='建议售价'),
    sa.Column('supplier', sa.String(length=100), nullable=True, comment='供应商'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['category_id'], ['inventory_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku'),
    comment='库存物品表'
    )
    op.create_table('inventory_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('item_id', sa.Integer(), nullable=False, comment='物品ID'),
    sa.Column('store_id', sa.Integer(), nullable=False, comment='所属门店'),
    sa.Column('change_type', sa.String(length=10), nullable=False, comment='变动类型: in(入库)/out(出库)/adjust(盘点调整)'),
    sa.Column('quantity_change', sa.Float(), nullable=False, comment='变动数量(正入负出)'),
    sa.Column('quantity_after', sa.Float(), nullable=False, comment='变动后数量'),
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='操作人'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='操作时间'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='库存流水日志表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_logs')
    op.drop_table('inventory_items')
    op.drop_table('inventory_categories')
    # ### end Alembic commands ###
