"""add_product_and_service_tables

Revision ID: 90459091ad0d
Revises: 8d85e8226903
Create Date: 2026-05-13 17:12:18.683035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90459091ad0d'
down_revision: Union[str, Sequence[str], None] = '8d85e8226903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('store_id', sa.Integer(), nullable=False, comment='所属门店'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='服务名称(如:基础洗护)'),
    sa.Column('category', sa.String(length=30), nullable=False, comment='服务分类: grooming(美容) / boarding(寄养) / medical(医疗) / training(训练) / other'),
    sa.Column('price', sa.Float(), nullable=False, comment='标准价格'),
    sa.Column('duration_minutes', sa.Integer(), nullable=True, comment='预计时长(分钟)'),
    sa.Column('description', sa.Text(), nullable=True, comment='服务说明'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否上架'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='服务项目表(美容/寄养/医疗/训练等)'
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('store_id', sa.Integer(), nullable=False, comment='所属门店'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='商品名称'),
    sa.Column('product_type', sa.String(length=20), nullable=False, comment='类型: goods(用品) / pet(活体)'),
    sa.Column('pet_id', sa.Integer(), nullable=True, comment='关联宠物(活体售卖时)'),
    sa.Column('inventory_item_id', sa.Integer(), nullable=True, comment='关联库存(用品售卖时)'),
    sa.Column('price', sa.Float(), nullable=False, comment='售价'),
    sa.Column('cost_price', sa.Float(), nullable=True, comment='成本价'),
    sa.Column('stock', sa.Integer(), nullable=True, comment='库存量(用品类，活体类固定为1)'),
    sa.Column('description', sa.Text(), nullable=True, comment='商品描述'),
    sa.Column('cover_image', sa.String(length=255), nullable=True, comment='封面图'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否上架'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='商品表(宠物用品/宠物活体售卖)'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('services')
    # ### end Alembic commands ###
