"""添加顾客和宠物模型

Revision ID: b8a146d43e7b
Revises: 4b7c84c8758c
Create Date: 2026-05-12 15:24:53.027968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8a146d43e7b'
down_revision: Union[str, Sequence[str], None] = '4b7c84c8758c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='关联基础用户'),
    sa.Column('real_name', sa.String(length=50), nullable=True, comment='客户真实姓名'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='联系地址(寄养接送需要)'),
    sa.Column('membership_level', sa.String(length=20), nullable=True, comment='会员等级'),
    sa.Column('points', sa.Integer(), nullable=True, comment='积分'),
    sa.Column('balance', sa.Float(), nullable=True, comment='账户余额'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    comment='客户业务档案表'
    )
    op.create_index(op.f('ix_customer_profiles_phone'), 'customer_profiles', ['phone'], unique=False)
    op.create_table('pets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='关联客户的主键'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='宠物昵称'),
    sa.Column('species', sa.String(length=20), nullable=False, comment='物种(狗/猫/异宠)'),
    sa.Column('breed', sa.String(length=50), nullable=True, comment='品种(如: 金毛/蓝猫)'),
    sa.Column('gender', sa.String(length=10), nullable=True, comment='性别(公/母/未知)'),
    sa.Column('weight', sa.Float(), nullable=True, comment='体重(kg)，影响洗护价格'),
    sa.Column('birth_date', sa.Date(), nullable=True, comment='出生日期(用于计算年龄和发生日祝福)'),
    sa.Column('is_neutered', sa.Boolean(), nullable=True, comment='是否绝育'),
    sa.Column('vaccine_status', sa.String(length=255), nullable=True, comment='疫苗接种状态描述或简述'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='宠物照片URL'),
    sa.Column('special_notes', sa.String(length=500), nullable=True, comment='特殊注意事项(如: 咬人/皮肤病/过敏史)'),
    sa.ForeignKeyConstraint(['owner_id'], ['customer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='宠物档案表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    op.drop_index(op.f('ix_customer_profiles_phone'), table_name='customer_profiles')
    op.drop_table('customer_profiles')
    # ### end Alembic commands ###
