"""添加门店和用户-门店关联表

Revision ID: c7f77ae5f35c
Revises: 57bf5d98004f
Create Date: 2026-05-13 15:05:41.007741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7f77ae5f35c'
down_revision: Union[str, Sequence[str], None] = '57bf5d98004f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='门店名称'),
    sa.Column('code', sa.String(length=20), nullable=False, comment='门店编码(如BJ001)'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='门店地址'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='门店联系电话'),
    sa.Column('manager_id', sa.Integer(), nullable=True, comment='店长用户ID'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否营业中'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    comment='门店信息表'
    )
    op.create_table('user_stores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('store_id', sa.Integer(), nullable=False, comment='门店ID'),
    sa.Column('is_primary', sa.Boolean(), nullable=True, comment='是否主属门店'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='绑定时间'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户-门店绑定表'
    )
    op.add_column('customer_profiles', sa.Column('store_id', sa.Integer(), nullable=True, comment='所属门店'))
    op.create_foreign_key(None, 'customer_profiles', 'stores', ['store_id'], ['id'], ondelete='SET NULL')
    op.add_column('pets', sa.Column('store_id', sa.Integer(), nullable=True, comment='所属门店'))
    op.create_foreign_key(None, 'pets', 'stores', ['store_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pets', type_='foreignkey')
    op.drop_column('pets', 'store_id')
    op.drop_constraint(None, 'customer_profiles', type_='foreignkey')
    op.drop_column('customer_profiles', 'store_id')
    op.drop_table('user_stores')
    op.drop_table('stores')
    # ### end Alembic commands ###
